name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Storybook
      run: npm run build-storybook
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Plum Design System ${{ github.ref }}
        body: |
          ## 🎉 New Release of Plum Design System
          
          ### What's Changed
          - Updated components and documentation
          - See [Storybook documentation](https://plumhq.github.io/design-system/) for full details
          
          ### Installation
          ```bash
          npm install @plumhq/design-system@${{ github.ref }}
          ```
          
          ### Links
          - 📚 [Documentation](https://plumhq.github.io/design-system/)
          - 🐛 [Report Issues](https://github.com/PlumHQ/design-system/issues)
          - 💬 [Discussions](https://github.com/PlumHQ/design-system/discussions)
        draft: false
        prerelease: false
